### ISSUE TITLE
Importing orion versions into conda-forge

### ISSUE THREAD

**Issue by oxydaemon** [conda-forge/prefect-feedstock#129]
### Comment:

Currently orion, which is listed as a pre-release on pypi, is not imported into conda-forge.

Is it possible to get the orion pre-releases imported on this feedstock as well?

Found some related docs on conda naming convention for pre-release:
https://github.com/conda-forge/cfep/blob/main/cfep-05.md

**Comment by madkinsz** [comment]
Hm, that note says that alpha/beta tags are not supported, only rc/dev tags. I'm pretty hesitant to go through the effort of including our pre-releases here. What value is conda adding for you?

**Comment by oxydaemon** [comment]
In 2.0a7, support for conda was added to Flow Runners - https://github.com/PrefectHQ/prefect/blob/orion/RELEASE-NOTES.md#flow-runners

It would be useful to have the prefect orion release available in conda channels also so we can us orion in conda with conda packages only (without using pip install)

One workaround currently is to use pip to install from pypi, inside the conda environment - however orion has a lot of dependencies, so it pulls in a lot of packages only used by orion, and mixing so many conda and pip packages is not optimal

**Comment by madkinsz** [comment]
I agree this would be nice, this is on our roadmap but may need to wait until the beta label is dropped.

**Comment by madkinsz** [comment]
This should be done in #136

**Comment by oxydaemon** [comment]
Nice, thanks for your great help!
