### ISSUE TITLE
Please remove me as a maintainer

### ISSUE THREAD

**Issue by zanieb** [conda-forge/prefect-feedstock#233]
### Comment:

@serinamarie would you mind removing me as a maintainer here at your leisure?

**Comment by zanieb** [comment]
@jamiezieziula by the way since ya'll are loosely taking ownership of the release pipeline you'll want to get a member of the platform team added here e.g. https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-user-username

**Comment by serinamarie** [comment]
@zanieb You should be removed now 👍
