### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by firerain42** [conda-forge/prefect-feedstock#262]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Please update the dependencies. The [requirements](https://github.com/PrefectHQ/prefect/blob/main/requirements.txt) of the pip package have been updated quite a bit in the last time (including `sqlalchemy` and `pydantic`). It would be great if the conda package also profited from that.

### Installed packages

```shell
NA
```

### Environment info

```shell
NA
```

**Comment by dan-blanchard** [comment]
I've noticed that if I install `prefect` with conda and then run `pip check`, `pip check` fails because of the dependency mismatch:

```bash
$ pip check

prefect 2.14.2 requires ujson, which is not installed.
prefect 2.14.2 has requirement websockets<12.0,>=10.4, but you have websockets 12.0.
```
