### ISSUE TITLE
Expected lag in new version being available?

### ISSUE THREAD

**Issue by cicdw** [conda-forge/prefect-feedstock#3]
Issue: In #2 I _believe_ I successfully updated `prefect` to `0.5.1` in `conda-forge`.  Additionally, the newest version appears on the `conda-forge` website: https://anaconda.org/conda-forge/prefect

However, locally, `conda` is not seeing this new version.  `conda search`, `conda update`, `conda clean`, etc. only find `prefect==0.5.0`.  Is there an expected lag here or am I missing something?

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : pre-test-me
    active env location : /usr/local/anaconda3/envs/pre-test-me
            shell level : 1
       user config file : /Users/chris/.condarc
 populated config files : /Users/chris/.condarc
          conda version : 4.5.11
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : /usr/local/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/anaconda/osx-64
                          https://conda.anaconda.org/anaconda/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /usr/local/anaconda3/pkgs
                          /Users/chris/.conda/pkgs
       envs directories : /usr/local/anaconda3/envs
                          /Users/chris/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.5 Darwin/17.6.0 OSX/10.13.5
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```
</details>

**cc:** @dhirschfeld

**Comment by cicdw** [comment]
I'm finding it now ¯\_(ツ)_/¯

**Comment by dhirschfeld** [comment]
I think it depends, but IIUC it can be up to ~20mins as they do some sort of caching

**Comment by dhirschfeld** [comment]
It looks like you manually opened that PR which is perfectly fine but if you're feeling lazy and don't mind a few hours wait the bot would have noticed a new version on pypi and automatically opened the PR for you. It wouldn't have picked up the changed `distributed` dep though.

**Comment by dhirschfeld** [comment]
If you want definitive answers the *real* `conda-forge` admins hang out at https://gitter.im/conda-forge/conda-forge.github.io and are pretty responsive to questions there.

**Comment by cicdw** [comment]
Ok awesome - thanks a lot for the help!  Yea I did it manually this time to try and internalize the process a little.
